### ISSUE TITLE
How to build quakejs of this version?

### ISSUE THREAD

**Issue by agkr234** [briancullinan/planet_quake#5]
Hi,
I'm trying to build this version of quakejs, but I couldn't.
First I followed "Compilation and installation" written on README.md and I got an error after typing a command below.
```
steam@agekara-VirtualBox:~$ git clone --recurse-submodules --remote-submodules git@github.com:briancullinan/planet_quake.git
error: unknown option `remote-submodules'
```
So, I downloaded the source code manually by typing in `git clone https://github.com/briancullinan/planet_quake.git` and copied emsdk of the latest version to `planet_quake/code/xquakejs/lib` and typed in the following commands.
```
./code/xquakejs/lib/emsdk/emsdk install latest-upstream
./code/xquakejs/lib/emsdk/emsdk activate latest

make PLATFORM=js
```

and then I tried to compiled it, but it failed.
I got the following output after typing in `make PLATFORM=js`
```
steam@agekara-VirtualBox:~/planet_quake$ make PLATFORM=js
make[1]: Entering directory '/home/steam/planet_quake'

Building quake3 in build/release-js-js:

  VERSION: 1.32e
  PLATFORM: js
  ARCH: js
  COMPILE_PLATFORM: linux
  COMPILE_ARCH: x86_64
  CC: code/xquakejs/lib/emsdk/upstream/emscripten/emcc

  CFLAGS:
    -Wall
    -fno-strict-aliasing
    -Wimplicit
    -Wstrict-prototypes
    -Icode/xquakejs/lib/emsdk/cache/wasm/include/SDL2
    -Icode/xquakejs/lib/emsdk/cache/wasm/include
    -Icode/xquakejs/lib/emsdk/cache/wasm-obj/include/SDL2
    -Icode/xquakejs/lib/emsdk/cache/wasm-obj/include
    -DNO_VM_COMPILED
    -DUSE_CODEC_VORBIS=1
    -O3
    -Oz
    --llvm-lto
    3
    -s
    WASM=1
    -s
    SAFE_HEAP=0
    -s
    DEMANGLE_SUPPORT=0
    -s
    ASSERTIONS=0
    -s
    AGGRESSIVE_VARIABLE_ELIMINATION=1
    -fPIC

  Output:
    build/release-js-js/quake3e.js

make[2]: Entering directory '/home/steam/planet_quake'
CC code/client/cl_cgame.c

"LLVM_ROOT = 'code/xquakejs/lib/emsdk/upstream/bin';NODE_JS = 'code/xquakejs/lib/emsdk/node/12.9.1_64bit/bin/node';BINARYEN_ROOT = 'code/xquakejs/lib/emsdk/upstream';EMSCRIPTEN_ROOT = 'code/xquakejs/lib/emsdk/upstream/emscripten'"

Traceback (most recent call last):
  File "code/xquakejs/lib/emsdk/upstream/emscripten/emcc.py", line 42, in <module>
    import emscripten
  File "/home/steam/planet_quake/code/xquakejs/lib/emsdk/upstream/emscripten/emscripten.py", line 25, in <module>
    from tools import shared
  File "/home/steam/planet_quake/code/xquakejs/lib/emsdk/upstream/emscripten/tools/shared.py", line 3407, in <module>
    generate_config(EM_CONFIG, first_time=True)
  File "/home/steam/planet_quake/code/xquakejs/lib/emsdk/upstream/emscripten/tools/shared.py", line 232, in generate_config
    with open(abspath, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/steam/planet_quake/"LLVM_ROOT = \'code/xquakejs/lib/emsdk/upstream/bin\';NODE_JS = \'code/xquakejs/lib/emsdk/node/12.9.1_64bit/bin/node\';BINARYEN_ROOT = \'code/xquakejs/lib/emsdk/upstream\';EMSCRIPTEN_ROOT = \'code/xquakejs/lib/emsdk/upstream/emscripten\'"'
Makefile:1469: recipe for target 'build/release-js-js/client/cl_cgame.o' failed
make[2]: *** [build/release-js-js/client/cl_cgame.o] Error 1
make[2]: Leaving directory '/home/steam/planet_quake'
Makefile:797: recipe for target 'targets' failed
make[1]: *** [targets] Error 2
make[1]: Leaving directory '/home/steam/planet_quake'
Makefile:771: recipe for target 'release' failed
make: *** [release] Error 2

```

It seems that "abspath" doesn't have the right path from what FileNotFoundError says, but I don't know how to fix it since I have no idea what path "abspath" should originally have.

or am I doing wrong during the steps before compiling the source code?
If someone have succeeded in compiling this code, I would like to know how to do it.
I'm using ubuntu 16.04 on VirtualBox.

Thanks.

**Comment by ugurcan377** [comment]
I also encountered the same error. Guessing from the traceback I thought it tried to create the config for `EM_CONFIG` env variable, but since I already installed emscripten manually and `EM_CONFIG` it set was already in my environment. It got the already existing value, hence the error.
Unsettting `EM_CONFIG` solved my problem.
